In [1]:
import pandas as pd

In [2]:
from datetime import datetime, timedelta

In [88]:
today = datetime.today() - timedelta(days=1)
str_today = today.strftime('%Y%m%d')

#str_today = '20170818'
str_today

'20170927'

In [89]:
excel_result = pd.read_excel('./raw_data/유형별시청형태_채널_GS SHOP_시간별_1d_' + str_today + '.xlsx', sheetname='유형별>시간별_시청가구상세테이블',index_col=None, header=2)

In [90]:
index =  range(1, len(excel_result)+1)

In [91]:
temp = []
for i in index:
    temp.append(i)

In [92]:
rearranged_excel = pd.DataFrame(excel_result, columns={'조회시간':'time','시청가구':'cnt'})

In [93]:
drop_nan = rearranged_excel.reset_index(temp,drop=True)

In [94]:
drop_nan.rename(columns={'조회시간':'time'}, inplace=True)

In [95]:
drop_nan.rename(columns={'시청가구':'cnt'}, inplace=True)

In [96]:
df3 = drop_nan[drop_nan.time != '일평균']

In [97]:
df3.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440],
           dtype='int64', length=1440)

In [98]:
df3_new = pd.DataFrame(df3, columns=['cnt','time'])

In [99]:
df3_new.iloc[:,1] = str_today + df3_new['time'].str.replace(r'(시|분)','')
#df3.loc['time'] = str_today + df3['time'].str.replace(r'(시|분)','')

In [100]:
df3_new

       cnt          time
1     8728  201709270000
2     8741  201709270001
3     9122  201709270002
4     9187  201709270003
5     8688  201709270004
6     7922  201709270005
7     7335  201709270006
8     7223  201709270007
9     7050  201709270008
10    7109  201709270009
11    6490  201709270010
12    6177  201709270011
13    5790  201709270012
14    5864  201709270013
15    5638  201709270014
16    5492  201709270015
17    5650  201709270016
18    5766  201709270017
19    6121  201709270018
20    6506  201709270019
21    6273  201709270020
22    5765  201709270021
23    5617  201709270022
24    5609  201709270023
25    5628  201709270024
26    5664  201709270025
27    5864  201709270026
28    6658  201709270027
29    7715  201709270028
30    7466  201709270029
...    ...           ...
1411  4087  201709272330
1412  3883  201709272331
1413  3718  201709272332
1414  3592  201709272333
1415  3469  201709272334
1416  3459  201709272335
1417  3490  201709272336
1418  3439  201709272337
1419  3445  201709272338
1420  3502  201709272339
1421  3372  201709272340
1422  3277  201709272341
1423  3216  201709272342
1424  3457  201709272343
1425  3490  201709272344
1426  3441  201709272345
1427  3681  201709272346
1428  3824  201709272347
1429  3521  201709272348
1430  3485  201709272349
1431  3345  201709272350
1432  3336  201709272351
1433  3274  201709272352
1434  3294  201709272353
1435  3546  201709272354
1436  3709  201709272355
1437  3487  201709272356
1438  3230  201709272357
1439  3366  201709272358
1440  3607  201709272359

[1440 rows x 2 columns]

In [101]:
temp_srvc = []
for i in range(len(df3)):
    #print(i)
    temp_srvc.append('L');

In [102]:
df3_new['srvc'] = temp_srvc

In [103]:
df3_new

       cnt          time srvc
1     8728  201709270000    L
2     8741  201709270001    L
3     9122  201709270002    L
4     9187  201709270003    L
5     8688  201709270004    L
6     7922  201709270005    L
7     7335  201709270006    L
8     7223  201709270007    L
9     7050  201709270008    L
10    7109  201709270009    L
11    6490  201709270010    L
12    6177  201709270011    L
13    5790  201709270012    L
14    5864  201709270013    L
15    5638  201709270014    L
16    5492  201709270015    L
17    5650  201709270016    L
18    5766  201709270017    L
19    6121  201709270018    L
20    6506  201709270019    L
21    6273  201709270020    L
22    5765  201709270021    L
23    5617  201709270022    L
24    5609  201709270023    L
25    5628  201709270024    L
26    5664  201709270025    L
27    5864  201709270026    L
28    6658  201709270027    L
29    7715  201709270028    L
30    7466  201709270029    L
...    ...           ...  ...
1411  4087  201709272330    L
1412  3883  201709272331    L
1413  3718  201709272332    L
1414  3592  201709272333    L
1415  3469  201709272334    L
1416  3459  201709272335    L
1417  3490  201709272336    L
1418  3439  201709272337    L
1419  3445  201709272338    L
1420  3502  201709272339    L
1421  3372  201709272340    L
1422  3277  201709272341    L
1423  3216  201709272342    L
1424  3457  201709272343    L
1425  3490  201709272344    L
1426  3441  201709272345    L
1427  3681  201709272346    L
1428  3824  201709272347    L
1429  3521  201709272348    L
1430  3485  201709272349    L
1431  3345  201709272350    L
1432  3336  201709272351    L
1433  3274  201709272352    L
1434  3294  201709272353    L
1435  3546  201709272354    L
1436  3709  201709272355    L
1437  3487  201709272356    L
1438  3230  201709272357    L
1439  3366  201709272358    L
1440  3607  201709272359    L

[1440 rows x 3 columns]

# CSV 추출

In [104]:
if df3_new['srvc'][1] == 'T':
    df3_new.to_csv('./raw_data/' + str_today + '_myshop_channel_hourly.csv', header=False)
else:
    df3_new.to_csv('./raw_data/' + str_today + '_gsshop_channel_hourly.csv', header=False)